version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex 
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=docker
    volumes:
      - /path/to/config:/config
      - /path/to/tv:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
    privileged: true
